import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flame/game.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';   // ← NEW: Firebase core init

import 'firebase_options.dart';                      // ← NEW: auto-generated by flutterfire configure
import 'game/state/game_state.dart';
import 'game/spider_slinger_game.dart';
import 'config/game_routes.dart';
import 'services/auth_service.dart';
import 'ui/overlays/user_registration_overlay.dart';
import 'ui/overlays/main_menu_overlay.dart';
import 'ui/overlays/hud_overlay.dart';
import 'ui/overlays/pause_menu_overlay.dart';
import 'ui/overlays/game_over_overlay.dart';
import 'ui/overlays/tutorial_overlay.dart';
import 'ui/screens/leaderboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock orientation to landscape
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight,
  ]);

  // ✅ STEP B: Initialize Firebase before runApp().
  // DefaultFirebaseOptions comes from the auto-generated firebase_options.dart.
  // This MUST be awaited — nothing Firebase-related works until this completes.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => GameState()),
      ],
      child: const SpiderSlingerApp(),
    ),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// SpiderSlingerApp is now a StatefulWidget so it can kick off the
// async auth sign-in and update GameState once the uid arrives.
// ─────────────────────────────────────────────────────────────────────────────
class SpiderSlingerApp extends StatefulWidget {
  const SpiderSlingerApp({super.key});

  @override
  State<SpiderSlingerApp> createState() => _SpiderSlingerAppState();
}

class _SpiderSlingerAppState extends State<SpiderSlingerApp> {
  // A single AuthService instance — reused for the lifetime of the app.
  final AuthService _authService = AuthService();

  @override
  void initState() {
    super.initState();
    _signInSilently();
  }

  // Signs the player in anonymously as soon as the app starts.
  // This is "silent" — the player never sees a login screen.
  // If they already signed in before, Firebase reuses the same uid automatically.
  Future<void> _signInSilently() async {
    final gameState = Provider.of<GameState>(context, listen: false);

    // Listen to Firebase's auth state stream.
    // If a session already exists (returning user), this fires immediately
    // with the cached user — no network round-trip needed.
    _authService.user.listen((appUser) {
      gameState.setUser(appUser);
    });

    // Trigger a fresh anonymous sign-in.
    // Firebase is smart: if this device already has an anonymous uid,
    // signInAnonymously() returns the SAME uid, not a new one.
    await _authService.signInAnonymously();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Spiderman : Web Slinger',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        fontFamily: 'Courier',
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const GameScreen(),
        GameRoutes.leaderboardRoute: (context) => const LeaderboardScreen(),
      },
    );
  }
}

class GameScreen extends StatelessWidget {
  const GameScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Selector<GameState, int>(
      selector: (_, gameState) => gameState.attempts,
      builder: (context, attempts, child) {
        final gameState = Provider.of<GameState>(context, listen: false);
        return Scaffold(
          body: GameWidget<SpiderSlingerGame>(
            key: ValueKey(attempts),
            game: SpiderSlingerGame(gameState: gameState),
            initialActiveOverlays: [
              attempts == 0 ? GameRoutes.registration : GameRoutes.mainMenu
            ],
            overlayBuilderMap: {
              GameRoutes.registration: (context, game) => UserRegistrationOverlay(game: game),
              GameRoutes.mainMenu: (context, game) => MainMenuOverlay(game: game),
              GameRoutes.hud: (context, game) => HudOverlay(game: game),
              GameRoutes.pauseMenu: (context, game) => PauseMenuOverlay(game: game),
              GameRoutes.gameOver: (context, game) => GameOverOverlay(game: game),
              GameRoutes.tutorial: (context, game) => TutorialOverlay(game: game),
            },
          ),
        );
      },
    );
  }
}
